#!/bin/bash

if [ -z "$PYFILE" ]; then
    echo "PYFILE environment variable is not set."
    exit 1
fi

python3 -m py_compile "$PYFILE"

if [ $? -eq 0 ]; then
    echo "Compiling $PYFILE ..."
mv "__pycache__/$PYFILE"* .
    rmdir "__pycache__"
else
echo "Compilation of $PYFILE failed."
exit 1
fi

